trigger:
  branches:
    include:
    - ccheetham/rework-pipeline
  paths:
    include:
    - metadata-versions

variables:
- name: tagv3
  value: 3.1.3
- name: tagv2
  value: 2.5.4

name: $(tagv3).$(tagv2)-$(Rev:r)

stages:
- stage: Deploy
  displayName: Deploy
  condition:
    not(eq(variables['build.reason'], 'PullRequest'))
  jobs:
  - job: push
    displayName: Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: |
        echo '2:'$(tagv2) > metadata-versions
        echo '3:'$(tagv3) >> metadata-versions
      displayName: Set Version
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        Dockerfile: Dockerfile-metadata
        containerRegistry: SteeltoeContainerRegistry
        repository: documentation-metadata
        tags: |
          $(Build.BuildNumber)
          latest
