#@data/values-schema
#@schema/type any=True
---
name: documentation
namespace: website
image_name: steeltoe.azurecr.io/documentation
image_tag: latest
container_port: 80
container_memory: 128Mi
container_cpu: 500m
service_port: 80
replica_count: 1
hostname: ""
tls_secret: ""
