#@data/values-schema
#@schema/type any=True
---
name: main-site
namespace: website
image_name: steeltoe.azurecr.io/main-site
image_tag: latest
container_port: 80
container_memory: 128Mi
container_cpu: 500m
service_port: 80
replica_count: 1
dotnet_environment: Development
hostname: ""
tls_secret: ""
